Repository crate/micropython-cratedb, pull requests merged in 2024-10, with the labels that each got.

#11 Added text for current example scripts.
  examples/README.md
Labels: documentation

#14 Adds example code and README updates showing how to manage container data types - OBJECT and ARRAY.
  README.md
  examples/README.md
  examples/object_examples.py
Labels: documentation

#16 Renames `microcrate` to `micropython-cratedb`.
  README.md
  cratedb.py
  examples/README.md
  examples/example_usage.py
  examples/object_examples.py
  examples/picow_demo.py
  package.json
Labels: chore

#19 Adds contributor guide and code of conduct files.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: chore

#20 Repo name updates.
  README.md
  package.json
Labels: chore

#21 Updated GitHub org name to crate.
  README.md
  package.json
Labels: chore, cla-signed

#23 Documentation about CPython. Make example programs work out of the box.
  .gitignore
  README.md
  docs/cpython.md
  examples/example_usage.py
  examples/object_examples.py
  examples/picow_demo.py
Labels: documentation, enhancement, cla-signed

#25 Tests: Add software tests and CI/GHA configuration
  .github/dependabot.yml
  .github/workflows/tests.yml
  .gitignore
  README.md
  examples/picow_demo.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  tests/test_examples.py
Labels: cla-signed

#26 Chore: Format code using Ruff. Satisfy and enable linter on CI.
  .github/workflows/tests.yml
  cratedb.py
  examples/example_usage.py
  examples/object_examples.py
  examples/picow_demo.py
  pyproject.toml
  tests/test_examples.py
Labels: cla-signed
